use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;

pub fn hooks_dir() -> Result<PathBuf> {
    let dir = dirs::home_dir()
        .context("no home dir")?
        .join(".grok")
        .join("hooks");
    fs::create_dir_all(&dir)?;
    Ok(dir)
}

/// Install command hooks that forward Grok events to Booster.
///
/// ## Critical Windows detail
///
/// Grok's hook runner treats any command string **with spaces** as a shell
/// command (`pwsh -Command …` / `cmd /C …`). PowerShell does **not** forward
/// stdin to the child, so `hook-forward` never sees the event JSON and Booster
/// stays on "waiting for hooks".
///
/// Fix: install a wrapper at a **space-free absolute path** under `~/.grok/hooks/`
/// and put *that path alone* in the JSON (no quotes, no args). Grok then uses
/// `Command::new(path)` and pipes stdin correctly.
pub fn install_hooks(port: u16) -> Result<PathBuf> {
    let dir = hooks_dir()?;
    let exe = std::env::current_exe().context("current_exe for hook install")?;
    let exe_str = exe.display().to_string();

    // Prefer a short space-free wrapper name under ~/.grok/hooks
    #[cfg(windows)]
    let wrapper_path = {
        let wrapper = dir.join("booster-fwd.cmd");
        // Also remove old name if present
        let _ = fs::remove_file(dir.join("booster-forward.cmd"));
        let body = format!(
            "@echo off\r\n\
             REM Auto-generated by grok-build-booster — do not edit by hand\r\n\
             REM stdin = Grok hook JSON → stdout = decision JSON\r\n\
             \"{exe}\" hook-forward --port {port}\r\n",
            exe = exe_str,
            port = port
        );
        fs::write(&wrapper, body)?;
        wrapper
    };

    #[cfg(not(windows))]
    let wrapper_path = {
        let wrapper = dir.join("booster-fwd.sh");
        let body = format!(
            "#!/usr/bin/env bash\n\
             # Auto-generated by grok-build-booster — do not edit by hand\n\
             exec \"{exe}\" hook-forward --port {port}\n",
            exe = exe_str,
            port = port
        );
        fs::write(&wrapper, body)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = fs::metadata(&wrapper)?.permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&wrapper, perms)?;
        }
        wrapper
    };

    // Absolute path, no spaces, no arguments → Grok direct spawn (not PowerShell).
    let command = wrapper_path
        .canonicalize()
        .unwrap_or(wrapper_path.clone())
        .to_string_lossy()
        .to_string();

    // Strip Windows \\?\ prefix if present (breaks some spawn paths)
    let command = command
        .strip_prefix(r"\\?\")
        .unwrap_or(&command)
        .to_string();

    if command.contains(' ') {
        anyhow::bail!(
            "hook wrapper path contains spaces ({command}); Grok would run it via PowerShell and break stdin. \
             Move GROK_HOME / user profile to a path without spaces, or set a junction."
        );
    }

    let value = hook_json_command(&command);
    let path = dir.join("grok-build-booster.json");
    fs::write(&path, serde_json::to_string_pretty(&value)?)?;
    Ok(path)
}

pub fn hook_json_command(command: &str) -> serde_json::Value {
    let entry = |timeout: u64| {
        serde_json::json!([{
            "hooks": [{
                "type": "command",
                "command": command,
                "timeout": timeout
            }]
        }])
    };

    // Observe + Stop only. No PreToolUse (blocking on every tool).
    serde_json::json!({
        "hooks": {
            "SessionStart": entry(8),
            "UserPromptSubmit": entry(15),
            "PostToolUse": entry(8),
            "PostToolUseFailure": entry(8),
            "SubagentStart": entry(8),
            "SubagentStop": entry(8),
            "Stop": entry(10),
            "StopFailure": entry(8),
            "SessionEnd": entry(8),
            "PreCompact": entry(8),
            "PostCompact": entry(8)
        }
    })
}

pub fn hook_json_for_port(port: u16, booster_exe: &str) -> serde_json::Value {
    // Test helper only — prefer install_hooks() in production.
    let cmd = format!("{booster_exe}");
    let _ = port;
    hook_json_command(&cmd)
}
